### ISSUE TITLE
Adding a side explorer

### ISSUE THREAD

**Issue by BnayaZil** [urish/vscode-tsquery#10]
A nice productive feature could be adding a side AST explorer option, the explorer will help to build the queries.

**Comment by urish** [comment]
Thanks for the suggestion! 

I actually have [started working on this](https://github.com/urish/vscode-tsquery/commit/ba289cde72e9d4d168d7614497298255a927885b), but still waiting for Microsoft/vscode#48198 to be released before completing this feature.

Meanwhile, you can check out [tsquery-playground](https://tsquery-playground.firebaseapp.com/) which provides similar functionality on the web.
